name: RT model history

on:
  push:
    branches: [ "main", 'refactor_naming']
jobs:
  memote-history:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout model
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.10'

    - name: Install memote
      run: pip install memote cobra

    - name: Setup variables
      id: setup
      run: |
        echo "snapshot=snapshot_report.html" >> $GITHUB_ENV
        echo "history=history_report.html" >> $GITHUB_ENV
        echo "deployment=gh-pages" >> $GITHUB_ENV
        echo "custom_tests=rtoru/custom_tests" >> $GITHUB_ENV
        echo "MEMOTE_LOCATION=Results" >> $GITHUB_ENV
        echo "PYTHONPATH=$PYTHONPATH:concerto_path" >> $GITHUB_ENV

    - name: Checkout concerto
      uses: actions/checkout@v2
      with:
        repository: PNNL-CompBio/CONCERTO
        path: concerto_path

    - name: Prep local repo
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        # make sure gh-pages is local
        git checkout gh-pages
        # back to main
        git checkout ${{ github.ref_name }}

    - name: run single point
      run: |
        pwd
        ls
        memote run --custom-tests=${{ env.custom_tests }}
        
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Compute Memote history on push
      run: |
        git checkout ${{ github.ref_name }}
        # Generate the history report on the deployment branch
        memote report history --filename="${{ env.history }}" \
            --deployment gh-pages
        git checkout gh-pages
        git add "${{ env.history }}"
        git commit -m 'chore: update memote history'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run snapshot report
      run: |
        git pull
        git status
        git checkout ${{ github.ref_name }}
        # generate snapshot/html report of model
        memote report snapshot \
        --filename="${{ env.snapshot }}" \
        --custom-tests=${{ env.custom_tests }}
        git branch
        git status
        ls
        git checkout gh-pages
        git add "${{ env.snapshot }}"
        git commit -m 'chore: update memote snapshot'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




#    - name: Auto-commit results
#      uses: stefanzweifel/git-auto-commit-action@v4.4.0
#      with:
#        commit_user_name: memote-bot
#        commit_message: "chore: update memote history report"
#        file_pattern: "*_report.html"
#        branch: gh-pages
#        repository: .
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}